"""Messaging infrastructure for workflow run operations.

This module provides NATS-based messaging for workflow lifecycle events,
enabling clients to start workflows and track execution through observable events.
"""

from grctl.models.api import GrctlAPIError, GrctlAPIResponse
from grctl.models.command import (
    CancelCmd,
    CmdKind,
    Command,
    DescribeCmd,
    EventCmd,
    StartCmd,
    command_decoder,
    command_encoder,
)
from grctl.models.directive import (
    Cancel,
    Complete,
    Directive,
    DirectiveKind,
    DirectiveMessage,
    Event,
    Fail,
    Sleep,
    SleepUntil,
    Start,
    Step,
    StepResult,
    WaitEvent,
    directive_decoder,
    directive_encoder,
)
from grctl.models.history import (
    ChildWorkflowStarted,
    DeterministicEvents,
    ErrorDetails,
    HistoryEvent,
    HistoryKind,
    ParentEventSent,
    RandomRecorded,
    RunCancelled,
    RunCompleted,
    RunEvents,
    RunFailed,
    RunScheduled,
    RunStarted,
    RunTimeout,
    SleepRecorded,
    StepCancelled,
    StepCompleted,
    StepEvents,
    StepFailed,
    StepStarted,
    StepTimeout,
    TaskAttemptFailed,
    TaskCancelled,
    TaskCompleted,
    TaskEvents,
    TaskFailed,
    TaskStarted,
    TimestampRecorded,
    UuidRecorded,
    history_decoder,
    history_encoder,
)
from grctl.models.run_info import RunInfo, RunStateKind, RunStatus
from grctl.models.run_info_helper import RunInfoManager

__all__ = [  # noqa: RUF022
    # API response types
    "GrctlAPIError",
    "GrctlAPIResponse",
    # Command types
    "Command",
    "StartCmd",
    "CancelCmd",
    "DescribeCmd",
    "EventCmd",
    "CmdKind",
    "command_decoder",
    "command_encoder",
    # Directive types
    "Directive",
    "DirectiveMessage",
    "DirectiveKind",
    "Start",
    "Cancel",
    "Event",
    "Complete",
    "Fail",
    "Step",
    "StepResult",
    "WaitEvent",
    "Sleep",
    "SleepUntil",
    "directive_decoder",
    "directive_encoder",
    # History event types
    "HistoryEvent",
    "HistoryKind",
    "RunScheduled",
    "RunStarted",
    "RunCompleted",
    "RunEvents",
    "RunFailed",
    "RunCancelled",
    "RunTimeout",
    "StepEvents",
    "StepStarted",
    "StepCompleted",
    "StepFailed",
    "StepCancelled",
    "StepTimeout",
    "TaskEvents",
    "TaskStarted",
    "TaskCompleted",
    "TaskFailed",
    "TaskAttemptFailed",
    "TaskCancelled",
    "DeterministicEvents",
    "TimestampRecorded",
    "RandomRecorded",
    "UuidRecorded",
    "SleepRecorded",
    "ChildWorkflowStarted",
    "ParentEventSent",
    "history_decoder",
    "history_encoder",
    # Common types
    "RunInfo",
    "RunStateKind",
    "RunStatus",
    "ErrorDetails",
    "RunInfoManager",
]
